"""empty message

Revision ID: 9175ae70c8fe
Revises: 
Create Date: 2021-01-03 20:11:12.460617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9175ae70c8fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trader', sa.Column('email', sa.String(length=128), nullable=False))
    op.create_index(op.f('ix_trader_email'), 'trader', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trader_email'), table_name='trader')
    op.drop_column('trader', 'email')
    # ### end Alembic commands ###
