"""empty message

Revision ID: b5b301f4ea25
Revises: 4a782bc6cabb
Create Date: 2021-01-03 21:01:40.483490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b301f4ea25'
down_revision = '4a782bc6cabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('code', sa.String(length=8), nullable=True))
    op.add_column('currency', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.drop_column('currency', 'name')
    op.drop_column('currency', 'code')
    # ### end Alembic commands ###
