"""empty message

Revision ID: e93908c0c43f
Revises: 9175ae70c8fe
Create Date: 2021-01-03 20:18:05.724005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93908c0c43f'
down_revision = '9175ae70c8fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trader', sa.Column('email', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_trader_email'), 'trader', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trader_email'), table_name='trader')
    op.drop_column('trader', 'email')
    # ### end Alembic commands ###
